[2025-01-24T21:14:20.274+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T21:14:20.284+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract_empresas manual__2025-01-24T20:59:53.324100+00:00 [queued]>
[2025-01-24T21:14:20.289+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract_empresas manual__2025-01-24T20:59:53.324100+00:00 [queued]>
[2025-01-24T21:14:20.336+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 5
[2025-01-24T21:14:20.382+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_empresas> on 2025-01-24 20:59:53.324100+00:00
[2025-01-24T21:14:20.387+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=995) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T21:14:20.388+0000] {standard_task_runner.py:72} INFO - Started process 1000 to run task
[2025-01-24T21:14:20.388+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract_empresas', 'manual__2025-01-24T20:59:53.324100+00:00', '--job-id', '806', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmp_f5mga6c']
[2025-01-24T21:14:20.390+0000] {standard_task_runner.py:105} INFO - Job 806: Subtask extract_empresas
[2025-01-24T21:14:20.418+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract_empresas manual__2025-01-24T20:59:53.324100+00:00 [running]> on host ee70781c29c7
[2025-01-24T21:14:20.469+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract_empresas' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T20:59:53.324100+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T20:59:53.324100+00:00'
[2025-01-24T21:14:20.470+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T21:14:20.482+0000] {logging_mixin.py:190} INFO - Data formatada: 2025-01
[2025-01-24T21:14:20.727+0000] {logging_mixin.py:190} INFO - Arquivos encontrados: ['Empresas0.zip', 'Empresas1.zip', 'Empresas2.zip', 'Empresas3.zip', 'Empresas4.zip', 'Empresas5.zip', 'Empresas6.zip', 'Empresas7.zip', 'Empresas8.zip', 'Empresas9.zip']
[2025-01-24T21:14:20.727+0000] {logging_mixin.py:190} INFO - Baixando o arquivo: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2025-01/Empresas0.zip
[2025-01-24T21:15:35.883+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-01-24T21:15:35.884+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-24T21:15:35.885+0000] {process_utils.py:132} INFO - Sending 15 to group 1000. PIDs of all processes in the group: [1000]
[2025-01-24T21:15:35.885+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1000
[2025-01-24T21:15:35.885+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-24T21:15:35.895+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T21:15:35.977+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1000, status='terminated', exitcode=0, started='21:14:19') (1000) terminated with exit code 0
